site_name: Antique War – Guide Utilisateur
site_description: Documentation officielle du jeu Antique War
site_author: Équipe Antique War
site_url: ""

theme:
  name: material
  language: fr
  palette:
    primary: amber
    accent: deep-orange
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - toc.integrate
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - abbr
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist

nav:
  - Accueil: index.md
  - Débuter:
      - Présentation du jeu: presentation.md
      - Objectif & Règles: objectifs.md
  - Jouer une Partie:
      - Menues Principaux: menus.md
      - Interface du jeu: interface.md
      - Unités: unites.md
      - Terrains & Obstacles: terrains.md
      - Économie & Ressources: economie.md
      - Évènements aléatoires: evenements.md
  - À propos:
      - Développeurs: equipe.md
