site_name: Antique War – Game Design
site_url: https://example.com
site_dir: public

theme:
  name: material
  language: fr
  palette:
    primary: amber
    accent: deep orange

nav:
  - Accueil: index.md
  - Présentation: presentation.md
  - Gameplay:
      - Jouer une partie: gameplay.md
  - Économie: economie.md
  - Unités: unites.md
  - Terrains et Obstacles: terrains.md
